[package]
name = "dovetail"
version = "0.1.0"
edition = "2024"
authors = ["David Loewe <49597367+TumbleOwlee@users.noreply.github.com>"]
license = "MIT"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
derive_builder = "0.20.2"
ferrowl-ui = { git = "https://github.com/tumbleowlee/ferrowl", version = "0.6.1" }
getset = "0.1.7"
itertools = "0.15.0"
ratatui = "0.30.2"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.5"
